name: Builder

on:
  push:
    branches: ['master']
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout twofactorauth repo
        uses: actions/checkout@v2
        with:
          repository: 2factorauth/twofactorauth
          path: twofactorauth
      
      - run: |
          npm install
          node ./index.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated"
          git push
